name: Build Release

on: 
  push:
    tags:
      - "v*"

jobs:
  merge_contracts_to_sqlite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Build G2
        run: |
          python merge_contracts_to_sqlite.py
      - name: Build G3
        run: |
          python v3/generate_abi_dbs.py
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset for G2
        id: upload-release-asset-g2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./contracts.zip
          asset_name: contracts.zip
          asset_content_type: application/zip
      - name: Upload Release Asset for G3
        id: upload-release-asset-g3
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./contracts_g3.zip
          asset_name: contracts_g3.zip
          asset_content_type: application/zip